// <auto-generated />
using AStar.Dev.OneDrive.Client.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AStar.Dev.OneDrive.Client.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251221055438_AddBytesTransferredToTransferLogs")]
    partial class AddBytesTransferredToTransferLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("AStar.Dev.OneDrive.Client.Core.Entities.DeltaToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastSyncedUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LastSyncedUtc_Ticks");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DeltaTokens", (string)null);
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Client.Core.Entities.DriveItemRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CTag")
                        .HasColumnType("TEXT");

                    b.Property<string>("DriveItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ETag")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFolder")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastModifiedUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LastModifiedUtc_Ticks");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DriveItemId");

                    b.ToTable("DriveItems", (string)null);
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Client.Core.Entities.LocalFileRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastWriteUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LastWriteUtc_Ticks");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SyncState")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RelativePath");

                    b.ToTable("LocalFiles", (string)null);
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Client.Core.Entities.TransferLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long?>("BytesTransferred")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CompletedUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CompletedUtc_Ticks");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("StartedUtc_Ticks");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TransferLogs", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
