// <auto-generated />
using System;
using AStar.Dev.OneDrive.Client.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AStar.Dev.OneDrive.Client.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260116223008_RenameTokenValueToToken")]
    partial class RenameTokenValueToToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("AStar.Dev.OneDrive.Client.Core.Entities.Account", b =>
                {
                    b.Property<string>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AutoSyncIntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeltaToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableDebugLogging")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableDetailedSyncLogging")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAuthenticated")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSyncUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalSyncPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxItemsInBatch")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxParallelUpDownloads")
                        .HasColumnType("INTEGER");

                    b.HasKey("AccountId");

                    b.HasIndex("LocalSyncPath")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Client.Core.Entities.DeltaToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("LastSyncedUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LastSyncedUtc_Ticks");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("DeltaTokens", (string)null);
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Client.Core.Entities.DriveItemRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CTag")
                        .HasColumnType("TEXT");

                    b.Property<string>("DriveItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ETag")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFolder")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastModifiedUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LastModifiedUtc_Ticks");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("DriveItemId");

                    b.ToTable("DriveItems", (string)null);
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Client.Core.Entities.FileMetadata", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CTag")
                        .HasColumnType("TEXT");

                    b.Property<string>("ETag")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastSyncDirection")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SyncStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("AccountId", "Path");

                    b.ToTable("FileMetadata");
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Client.Core.Entities.LocalFileRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .HasColumnType("TEXT");

                    b.Property<long>("LastWriteUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LastWriteUtc_Ticks");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SyncState")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("RelativePath");

                    b.ToTable("LocalFiles", (string)null);
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Client.Core.Entities.SyncConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "FolderPath");

                    b.ToTable("SyncConfiguration");
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Client.Core.Entities.SyncConflict", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LocalModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("LocalSize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RemoteModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("RemoteSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResolutionStrategy")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("AccountId", "IsResolved");

                    b.ToTable("SyncConflict");
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Client.Core.Entities.TransferLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("BytesTransferred")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CompletedUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CompletedUtc_Ticks");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("StartedUtc_Ticks");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("TransferLogs", (string)null);
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Client.Core.Entities.WindowPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Height")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(600.0);

                    b.Property<bool>("IsMaximized")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Width")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(800.0);

                    b.Property<double?>("X")
                        .HasColumnType("REAL");

                    b.Property<double?>("Y")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("WindowPreferences");
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Client.Core.Entities.DeltaToken", b =>
                {
                    b.HasOne("AStar.Dev.OneDrive.Client.Core.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Client.Core.Entities.DriveItemRecord", b =>
                {
                    b.HasOne("AStar.Dev.OneDrive.Client.Core.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Client.Core.Entities.FileMetadata", b =>
                {
                    b.HasOne("AStar.Dev.OneDrive.Client.Core.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Client.Core.Entities.LocalFileRecord", b =>
                {
                    b.HasOne("AStar.Dev.OneDrive.Client.Core.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Client.Core.Entities.SyncConfiguration", b =>
                {
                    b.HasOne("AStar.Dev.OneDrive.Client.Core.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Client.Core.Entities.SyncConflict", b =>
                {
                    b.HasOne("AStar.Dev.OneDrive.Client.Core.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Client.Core.Entities.TransferLog", b =>
                {
                    b.HasOne("AStar.Dev.OneDrive.Client.Core.Entities.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
