using System;
using System.Collections.Generic;
using System.Text;

namespace AStar.Dev.Source.Generators;

internal static class OptionsBindingCodeGenerator
{
    public static string Generate(
        OptionsBindingGenerator.OptionsModel model,
        Dictionary<string, Dictionary<string, OptionsBindingGenerator.SchemaEntry>> schema)
    {
        var sb = new StringBuilder();
        AppendFileHeader(sb);
        AppendNamespace(sb, model.Namespace);
        AppendUsings(sb);

        Dictionary<string, OptionsBindingGenerator.SchemaEntry> sectionMap = GetSectionMap(schema, model.SectionName);

        AppendRegistrationClass(sb, model, sectionMap);

        return sb.ToString();
    }

    private static void AppendFileHeader(StringBuilder sb) => _ = sb.AppendLine("// <auto-generated/>");

    private static void AppendNamespace(StringBuilder sb, string? ns)
    {
        if(ns is not null)
            _ = sb.AppendLine($"namespace {ns};").AppendLine();
    }

    private static void AppendUsings(StringBuilder sb)
    {
        _ = sb.AppendLine("using System;");
        _ = sb.AppendLine("using System.Collections.Generic;");
        _ = sb.AppendLine("using System.ComponentModel.DataAnnotations;");
        _ = sb.AppendLine("using Microsoft.Extensions.Configuration;");
        _ = sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        _ = sb.AppendLine("using Microsoft.Extensions.Options;");
        _ = sb.AppendLine();
    }

    private static Dictionary<string, OptionsBindingGenerator.SchemaEntry> GetSectionMap(
        Dictionary<string, Dictionary<string, OptionsBindingGenerator.SchemaEntry>> schema,
        string sectionName)
    {
        _ = schema.TryGetValue(sectionName, out Dictionary<string, OptionsBindingGenerator.SchemaEntry>? sectionMap);
        return sectionMap ?? new Dictionary<string, OptionsBindingGenerator.SchemaEntry>(StringComparer.Ordinal);
    }

    private static void AppendRegistrationClass(
        StringBuilder sb,
        OptionsBindingGenerator.OptionsModel model,
        Dictionary<string, OptionsBindingGenerator.SchemaEntry> sectionMap)
    {
        _ = sb.AppendLine($"public static class {model.TypeName}OptionsRegistration");
        _ = sb.AppendLine("{");
        AppendRegistrationMethod(sb, model, sectionMap);
        _ = sb.AppendLine("}");
    }

    private static void AppendRegistrationMethod(
        StringBuilder sb,
        OptionsBindingGenerator.OptionsModel model,
        Dictionary<string, OptionsBindingGenerator.SchemaEntry> sectionMap)
    {
        _ = sb.AppendLine($"    public static IServiceCollection Add{model.TypeName}(this IServiceCollection s, IConfiguration cfg)");
        _ = sb.AppendLine("    {");

        AppendConfigurationBinding(sb, model);
        AppendDefaultAssignments(sb, model, sectionMap);
        AppendValidation(sb, model, sectionMap);
        AppendServiceRegistration(sb, model);

        _ = sb.AppendLine("        return s;");
        _ = sb.AppendLine("    }");
    }

    private static void AppendConfigurationBinding(StringBuilder sb, OptionsBindingGenerator.OptionsModel model)
    {
        var escapedSection = StringEscaper.Escape(model.SectionName);
        _ = sb.AppendLine($"        var section = cfg.GetSection(\"{escapedSection}\");");
        _ = sb.AppendLine($"        var opts = section.Get<{model.TypeName}>() ?? new {model.TypeName}();");
    }

    private static void AppendDefaultAssignments(
        StringBuilder sb,
        OptionsBindingGenerator.OptionsModel model,
        Dictionary<string, OptionsBindingGenerator.SchemaEntry> sectionMap)
    {
        foreach(OptionsBindingGenerator.PropModel prop in model.Properties)
        {
            if(sectionMap.TryGetValue(prop.Name, out OptionsBindingGenerator.SchemaEntry? entry) &&
                entry.DefaultValue is string defaultValue)
            {
                var assignment = DefaultAssignmentBuilder.Build(prop, defaultValue);
                if(assignment is not null)
                    _ = sb.AppendLine(assignment);
            }
        }
    }

    private static void AppendValidation(
        StringBuilder sb,
        OptionsBindingGenerator.OptionsModel model,
        Dictionary<string, OptionsBindingGenerator.SchemaEntry> sectionMap)
    {
        _ = sb.AppendLine("        var results = new List<ValidationResult>();");
        _ = sb.AppendLine("        var ok = Validator.TryValidateObject(opts, new ValidationContext(opts), results, validateAllProperties: true);");

        AppendSchemaRequiredChecks(sb, model, sectionMap);

        _ = sb.AppendLine("        if (!ok)");
        _ = sb.AppendLine($"            throw new OptionsValidationException(\"{model.TypeName}\", typeof({model.TypeName}), results.ConvertAll(r => r.ErrorMessage ?? \"Invalid\"));");
    }

    private static void AppendSchemaRequiredChecks(
        StringBuilder sb,
        OptionsBindingGenerator.OptionsModel model,
        Dictionary<string, OptionsBindingGenerator.SchemaEntry> sectionMap)
    {
        foreach(OptionsBindingGenerator.PropModel prop in model.Properties)
        {
            if(sectionMap.TryGetValue(prop.Name, out OptionsBindingGenerator.SchemaEntry? entry) && entry.IsRequired)
            {
                var check = RequiredCheckBuilder.Build(prop);
                if(check is not null)
                    _ = sb.AppendLine(check);
            }
        }
    }

    private static void AppendServiceRegistration(StringBuilder sb, OptionsBindingGenerator.OptionsModel model) => _ = sb.AppendLine($"        s.Configure<{model.TypeName}>(section);");
}
