using System;
using System.Text;

namespace AStar.Dev.Source.Generators;

internal static class StrongIdCodeGenerator
{
    public static string Generate(StrongIdGenerator.StrongIdModel model)
    {
        var sb = new StringBuilder();

        AppendFileHeader(sb);
        AppendNamespace(sb, model.Namespace);
        AppendStrongIdStruct(sb, model);

        return sb.ToString();
    }

    private static void AppendFileHeader(StringBuilder sb)
    {
        _ = sb.AppendLine("// <auto-generated/>");
        _ = sb.AppendLine("#nullable enable");
    }

    private static void AppendNamespace(StringBuilder sb, string? ns)
    {
        if(ns is not null)
            _ = sb.AppendLine($"namespace {ns};").AppendLine();
    }

    private static void AppendStrongIdStruct(StringBuilder sb, StrongIdGenerator.StrongIdModel model)
    {
        var accessibility = model.Accessibility.ToString().ToLowerInvariant();
        var underlyingType = model.UnderlyingTypeDisplay;

        _ = sb.AppendLine($"{accessibility} readonly partial struct {model.Name} : System.IEquatable<{model.Name}>");
        _ = sb.AppendLine("{");

        AppendStructBody(sb, model, underlyingType);

        _ = sb.AppendLine("}");
    }

    private static void AppendStructBody(StringBuilder sb, StrongIdGenerator.StrongIdModel model, string underlyingType)
    {
        AppendFieldAndConstructor(sb, model.Name, underlyingType);
        AppendConversionOperators(sb, model.Name, underlyingType);
        AppendEqualityMembers(sb, model.Name, underlyingType);
        AppendToStringMethod(sb, underlyingType);

        if(IsGuidType(underlyingType))
            AppendGuidHelpers(sb, model.Name);
    }

    private static void AppendFieldAndConstructor(StringBuilder sb, string name, string underlyingType)
    {
        _ = sb.AppendLine($"    private readonly {underlyingType} _value;");
        _ = sb.AppendLine($"    public {name}({underlyingType} value) => _value = value;");
        _ = sb.AppendLine();
    }

    private static void AppendConversionOperators(StringBuilder sb, string name, string underlyingType)
    {
        _ = sb.AppendLine($"    public static implicit operator {underlyingType}({name} id) => id._value;");
        _ = sb.AppendLine($"    public static explicit operator {name}({underlyingType} value) => new(value);");
        _ = sb.AppendLine();
    }

    private static void AppendEqualityMembers(StringBuilder sb, string name, string underlyingType)
    {
        _ = sb.AppendLine($"    public bool Equals({name} other) => System.Collections.Generic.EqualityComparer<{underlyingType}>.Default.Equals(_value, other._value);");
        _ = sb.AppendLine($"    public override bool Equals(object? obj) => obj is {name} other && Equals(other);");

        var getHashCodeBody = BuildGetHashCodeExpression(underlyingType);
        _ = sb.AppendLine($"    public override int GetHashCode() => {getHashCodeBody};");
    }

    private static void AppendToStringMethod(StringBuilder sb, string underlyingType)
    {
        var toStringBody = BuildToStringExpression(underlyingType);
        _ = sb.AppendLine($"    public override string ToString() => {toStringBody};");
    }

    private static void AppendGuidHelpers(StringBuilder sb, string name)
    {
        _ = sb.AppendLine();
        _ = sb.AppendLine($"    public static {name} New() => new(System.Guid.NewGuid());");
        _ = sb.AppendLine();
        _ = sb.AppendLine($"    public static bool TryParse(string? s, out {name} value)");
        _ = sb.AppendLine("    {");
        _ = sb.AppendLine("        var ok = System.Guid.TryParse(s, out var g);");
        _ = sb.AppendLine("        value = ok ? new(g) : default;");
        _ = sb.AppendLine("        return ok;");
        _ = sb.AppendLine("    }");
    }

    private static bool IsGuidType(string underlyingType) => string.Equals(underlyingType, "System.Guid", StringComparison.Ordinal) ||
               string.Equals(underlyingType, "Guid", StringComparison.Ordinal);

    private static bool IsStringType(string underlyingType) => string.Equals(underlyingType, "System.String", StringComparison.Ordinal) ||
               string.Equals(underlyingType, "string", StringComparison.Ordinal);

    private static string BuildToStringExpression(string underlyingType) => IsStringType(underlyingType)
            ? "_value ?? string.Empty"
            : "_value.ToString()";

    private static string BuildGetHashCodeExpression(string underlyingType) => IsStringType(underlyingType)
            ? "(_value == null ? 0 : _value.GetHashCode())"
            : $"System.Collections.Generic.EqualityComparer<{underlyingType}>.Default.GetHashCode(_value)";
}
